import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'
import { apiUrl } from '../services/apiUrl'
export type AppUser = { id: string; firstName: string; lastName: string; email: string; country: string | null; createdAt: string }
type Credentials = { email: string; password: string }; type SignUp = Credentials & { firstName: string; lastName: string; country?: string }
type Auth = { user: AppUser | null; ready: boolean; login: (input: Credentials) => Promise<void>; signup: (input: SignUp) => Promise<void>; logout: () => Promise<void>; requestSignIn: () => void; closeSignInPrompt: () => void; signInPromptOpen: boolean }
const Context = createContext<Auth | null>(null); const key = 'gotogether.session-token'
async function api<T>(path: string, options?: RequestInit, token?: string | null) { const response = await fetch(apiUrl(path), { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options?.headers } }); const body = response.status === 204 ? null : await response.json() as { data?: T; error?: string }; if (!response.ok) throw new Error(body?.error || 'Something went wrong.'); return body?.data as T }
export function AuthProvider({ children }: { children: ReactNode }) { const [user, setUser] = useState<AppUser | null>(null); const [ready, setReady] = useState(false); const [signInPromptOpen, setSignInPromptOpen] = useState(false); useEffect(() => { const token = localStorage.getItem(key); if (!token) { setReady(true); return } api<AppUser>('/auth/me', undefined, token).then(setUser).catch(() => localStorage.removeItem(key)).finally(() => setReady(true)) }, []); const apply = async (path: '/auth/login' | '/auth/signup', input: Credentials | SignUp) => { const result = await api<{ user: AppUser; token: string }>(path, { method: 'POST', body: JSON.stringify(input) }); localStorage.setItem(key, result.token); localStorage.setItem('gotogether.current-user-id', result.user.id); setUser(result.user) }; const logout = async () => { const token = localStorage.getItem(key); try { if (token) await api('/auth/logout', { method: 'POST' }, token) } finally { localStorage.removeItem(key); localStorage.removeItem('gotogether.current-user-id'); setUser(null) } }; return <Context.Provider value={{ user, ready, login: (input) => apply('/auth/login', input), signup: (input) => apply('/auth/signup', input), logout, requestSignIn: () => setSignInPromptOpen(true), closeSignInPrompt: () => setSignInPromptOpen(false), signInPromptOpen }}>{children}</Context.Provider> }
export const useAuth = () => { const context = useContext(Context); if (!context) throw new Error('useAuth must be used within AuthProvider'); return context }
