import { useState } from 'react'
import type { JourneyResponse, JourneyVote, QuestJourney } from '../apis/quests'
import { ItineraryInsights } from './ItineraryInsights'
import { TravelPlanningOptions } from './TravelPlanningOptions'
import { Icon } from './Ui'
import { photoFallback, recommendationPhoto } from '../services/itineraryPresentation'

const reactions = [['love', 'Love it'], ['works', 'Works for me'], ['concern', 'Concern']] as const
export function GroupResponses({ response, busy, onRespond }: { response: JourneyResponse; busy: boolean; onRespond: (reaction: JourneyVote['reaction'], note: string) => Promise<void> }) {
  const mine = response.people.find(person => person.isMe)
  const [note, setNote] = useState(mine?.note ?? '')
  const [concern, setConcern] = useState(false)
  const [responseError, setResponseError] = useState('')
  const send = async (reaction: JourneyVote['reaction'], note: string) => { setResponseError(''); try { await onRespond(reaction, note); setConcern(false) } catch (reason) { setResponseError(reason instanceof Error ? reason.message : 'Your response could not save. Please try again.') } }
  return <div className="group-responses"><div className="group-response-heading"><strong>{response.agreed ? 'Works for everyone' : `${response.answered} responses · ${response.concerns ? `${response.concerns} concern${response.concerns > 1 ? 's' : ''}` : 'Every voice counts'}`}</strong><div className="group-avatars">{response.people.map(person => <span key={person.id} className={person.reaction ? `is-${person.reaction}` : ''} title={`${person.name}: ${person.reaction ? reactions.find(([key]) => key === person.reaction)?.[1] : 'Waiting for a response'}`}>{person.name.slice(0, 1)}</span>)}</div></div><div className="group-reaction-buttons">{reactions.map(([key, label]) => <button type="button" key={key} aria-pressed={mine?.reaction === key} disabled={busy} onClick={() => key === 'concern' ? setConcern(true) : void send(key, '')}><Icon name={key === 'love' ? 'heart' : key === 'works' ? 'check' : 'chat'} size={16} />{label}</button>)}</div>{concern && <form className="group-concern" onSubmit={event => { event.preventDefault(); void send('concern', note) }}><label>What would make this work better? <span>Optional · shared with your crew</span><textarea value={note} onChange={event => setNote(event.target.value)} maxLength={600} rows={2} /></label><button type="submit" disabled={busy}>Share concern</button><button type="button" onClick={() => setConcern(false)}>Cancel</button></form>}{responseError && <p className="form-error" role="alert">{responseError}</p>}{response.people.filter(person => person.reaction === 'concern').map(person => <p className="group-concern-note" key={person.id}><strong>{person.name}:</strong> {person.note || 'Would like to discuss another option.'}</p>)}</div>
}

export function GroupOptions({ journey, busy, onRespond, onChoose, onDiscuss, currentId, roomId }: { roomId?: string; journey: QuestJourney; busy: boolean; onRespond: (vote: JourneyVote) => Promise<void>; onChoose?: (id: string) => void; onDiscuss?: (label: string, detail: string) => void; currentId?: string }) {
  const solo = journey.totalMembers === 1
  const selectionKey = `gotogether.option-preview.${roomId ?? journey.preferenceVersion}`
  const readSelection = (field: string, fallback: string) => { try { return sessionStorage.getItem(`${selectionKey}.${field}`) || fallback } catch { return fallback } }
  const remember = (field: string, value: string) => { try { sessionStorage.setItem(`${selectionKey}.${field}`, value) } catch { /* Browsing remains available without storage. */ } }
  const [view, updateView] = useState(() => readSelection('view', 'recommended'))
  const setView = (value: string) => { updateView(value); remember('view', value); setDay('all') }
  const [selectedId, setSelectedId] = useState(() => readSelection('id', ''))
  const [search, setSearch] = useState('')
  const [day, setDay] = useState<number | 'all'>('all')
  const options = (view === 'all' ? journey.allResults : journey.results).filter(trip => `${trip.destination} ${trip.title} ${trip.country}`.toLowerCase().includes(search.toLowerCase()))
  const selected = options.find(trip => trip.id === selectedId) ?? options[0]
  const select = (id: string) => { setSelectedId(id); remember('id', id); setDay('all') }
  if (!journey.ready) return <div className="group-empty"><Icon name="people" size={34} /><h2>{solo ? <>Let’s make this<br /><em>your kind of trip.</em></> : <>Good plans make room<br />for <em>every voice.</em></>}</h2><p>{solo ? 'Add your travel style in Your trip to find itineraries that fit you.' : `${journey.memberCount} of ${journey.totalMembers} travellers have confirmed their preferences. Your group’s matches will appear here when everyone is ready.`}</p>{!solo && <p>Keep collecting ideas and talking with your crew in the meantime.</p>}</div>
  if (!journey.allResults.length) return <div className="group-empty"><Icon name="compass" size={34} /><h2>Let’s find some<br /><em>common ground.</em></h2>{journey.blockers.map(message => <p key={message}>{message}</p>)}<p>{solo ? 'Open Your trip to adjust your preferences or save ideas for later.' : 'Open Your crew to update your own preferences, or talk through the choices in Crew chat. Nobody’s limits are silently relaxed.'}</p></div>
  const days = selected && Array.isArray(selected.daily_plan) ? selected.daily_plan as { day?: number; morning?: string; afternoon?: string; evening?: string; description?: string }[] : []
  return <section className="group-options"><header className="group-section-heading"><div><p className="eyebrow">{solo ? 'A LITTLE MORE YOU, IN EVERY DAY' : `ALL ${journey.totalMembers} VOICES, ONE ADVENTURE`}</p><h2>A few ways to<br /><em>{solo ? 'follow your curiosity.' : 'go together.'}</em></h2><p>{solo ? 'Explore every day, pick your favourite, and make it your own.' : 'Switch between options. Explore every day. Find the one that works for your people.'}</p></div><span className="group-count"><Icon name="check" size={15} />{journey.allResults.length} matching itineraries</span></header>
    <div className="group-option-controls"><div role="group" aria-label="Itinerary collection"><button aria-pressed={view === 'recommended'} onClick={() => { setView('recommended'); setSearch('') }}>Recommended</button><button aria-pressed={view === 'all'} onClick={() => setView('all')}>All matching itineraries ({journey.allResults.length})</button></div>{view === 'all' && <label><Icon name="compass" size={16} /><input aria-label="Find an itinerary" value={search} onChange={event => { setSearch(event.target.value); setDay('all') }} placeholder="Find a destination or itinerary" /></label>}</div>
    <div className="group-option-grid" role="group" aria-label="Choose an itinerary to preview">{options.map(trip => <button key={trip.id} data-itinerary-id={trip.id} className={`group-option-card${selected?.id === trip.id ? ' is-selected' : ''}`} aria-pressed={selected?.id === trip.id} onClick={() => select(trip.id)}><div className="group-option-photo"><img src={recommendationPhoto(trip)} alt="" onError={photoFallback} loading={view === 'recommended' ? 'eager' : 'lazy'} /><span>{trip.label}</span>{trip.id === currentId && <small>Current plan</small>}</div><div><p>{trip.country} · {trip.duration_days} days</p><h3>{trip.destination}<Icon name={selected?.id === trip.id ? 'check' : 'arrow'} size={18} /></h3><span>{trip.budget} · {trip.title}</span></div></button>)}</div>
    {!selected && <p role="status">No matching itinerary has that name. Try another search.</p>}
    {selected && <article className="group-itinerary-detail" key={selected.id} aria-label={`${selected.destination} full itinerary`}><header><div><p className="eyebrow">{selected.label}</p><h2>{selected.title}</h2><p>{selected.short_description}</p></div><div className="group-estimate"><span>{selected.duration_days} days · {selected.budget}</span><strong>{new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(selected.estimated_cost_usd)}</strong><small>Catalogue estimate per person.<br />Confirm inclusions, prices and availability.</small></div></header>
      <div className="group-fit-notes"><div><Icon name="people" size={20} /><strong>{solo ? 'Your travel style' : 'For your group'}{selected.score != null ? ` · ${selected.score}/100 fit` : ''}</strong><p>{selected.matchedPreferences.join(' · ') || (solo ? 'A mix of experiences within your preferences.' : 'A different mix of experiences within your shared requirements.')}</p></div><div><Icon name="heart" size={20} /><strong>For you</strong><p>{selected.personalFit != null ? `${selected.personalFit}/100 preference fit. This is a planning score, not a guarantee.` : solo ? 'Matched to your preferences.' : 'Your preferences are included in the shared match.'}</p></div><div><Icon name="sliders" size={20} /><strong>The trade-off</strong><p>{selected.compromises.join(' ')}</p></div></div>
      <div className="group-day-tabs" role="group" aria-label="Preview itinerary days"><button aria-pressed={day === 'all'} onClick={() => setDay('all')}>Full itinerary</button>{days.map((_, index) => <button key={index} aria-pressed={day === index} onClick={() => setDay(index)}>Day {index + 1}</button>)}</div>
      <div className="group-preview-days">{days.map((value, index) => (day === 'all' || day === index) && <section key={index} className="group-preview-day"><div><span>{String(index + 1).padStart(2, '0')}</span><h3>Day {index + 1}</h3>{!solo && onDiscuss && <button onClick={() => onDiscuss(`Day ${index + 1} · ${selected.destination}`, [value.morning, value.afternoon, value.evening].filter(Boolean).join(' · '))} aria-label={`Discuss day ${index + 1}`}><Icon name="chat" size={17} /></button>}</div>{value.description && <p>{value.description}</p>}{(['morning', 'afternoon', 'evening'] as const).map(slot => value[slot] && <article key={slot}><Icon name={slot === 'morning' ? 'sun' : slot === 'afternoon' ? 'sunset' : 'moon'} size={18} /><div><small>{slot}</small><p>{value[slot]}</p></div></article>)}</section>)}</div>
      <div className="group-option-decision">{!solo && <GroupResponses key={`${selected.id}:${journey.preferenceVersion}`} response={journey.options[selected.id]} busy={busy} onRespond={(reaction, note) => onRespond({ kind: 'option', optionId: selected.id, version: journey.preferenceVersion, reaction, note })} />}<div className="group-choose"><p>{solo ? 'Choose this starting point. You can edit, reorder or replace it whenever you like.' : journey.options[selected.id].agreed ? 'Everyone has responded positively. Your host can make this the shared itinerary.' : 'Everyone responds before the host chooses. Switching previews never changes your saved plan.'}</p>{onChoose && selected.id !== currentId && <button className="primary-button" disabled={busy || !solo && !journey.options[selected.id].agreed} onClick={() => onChoose(selected.id)}>{currentId ? 'Use this itinerary instead' : solo ? 'Make this my plan' : 'Make this our plan'}<Icon /></button>}{selected.id === currentId && <span><Icon name="check" size={16} />Your current starting itinerary</span>}</div></div>
      {roomId && <ItineraryInsights key={`${selected.id}:${journey.preferenceVersion}`} trip={selected} roomId={roomId} version={journey.preferenceVersion} />}
      <TravelPlanningOptions trip={selected} />
    </article>}
  </section>
}
