import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { createQuestPick, getQuestShortlist, reactToQuestPick, shareQuestPick, type PickReaction, type PickType, type SharedPick, type ShortlistData } from '../apis/quests'
import { Icon } from './Ui'

const category: Record<PickType, string> = { flight: 'Getting there', stay: 'Where we stay', activity: 'What we do', itinerary: 'Full journeys' }
const labels: Record<PickReaction, string> = { love: 'Love it', works: 'Works for me', not_for_me: 'Not for me' }
const demo: ShortlistData = { members: [{ id: 'me', name: 'You' }, { id: 'mira', name: 'Mira' }, { id: 'noah', name: 'Noah' }, { id: 'ria', name: 'Ria' }, { id: 'sam', name: 'Sam' }], myPicks: [], sharedShortlist: [
  { id: 'demo-flight', type: 'flight', title: 'Morning flight to Kyoto', destination: 'Delhi → Kyoto', estimatedPrice: 42000, note: 'Enough time to settle in before dinner.', link: null, imageUrl: null, createdAt: '', addedBy: { id: 'mira', name: 'Mira' }, groupFit: { responseCount: 5, loveCount: 3, worksCount: 2, notForMeCount: 0, missingResponses: 0, hardConflict: false, status: 'aligned' }, reactions: [{ userId: 'me', name: 'You', reaction: 'love', note: null, isMe: true }, { userId: 'mira', name: 'Mira', reaction: 'love', note: null, isMe: false }, { userId: 'noah', name: 'Noah', reaction: 'works', note: null, isMe: false }, { userId: 'ria', name: 'Ria', reaction: 'love', note: null, isMe: false }, { userId: 'sam', name: 'Sam', reaction: 'works', note: null, isMe: false }] },
  { id: 'demo-stay', type: 'stay', title: 'Nishiki courtyard stay', destination: 'Kyoto', estimatedPrice: 18000, note: 'Quiet rooms close to the market.', link: null, imageUrl: null, createdAt: '', addedBy: { id: 'noah', name: 'Noah' }, groupFit: { responseCount: 4, loveCount: 2, worksCount: 2, notForMeCount: 0, missingResponses: 1, hardConflict: false, status: 'nearly_aligned' }, reactions: [{ userId: 'me', name: 'You', reaction: 'love', note: null, isMe: true }, { userId: 'mira', name: 'Mira', reaction: 'works', note: null, isMe: false }, { userId: 'noah', name: 'Noah', reaction: 'love', note: null, isMe: false }, { userId: 'ria', name: 'Ria', reaction: 'works', note: null, isMe: false }, { userId: 'sam', name: 'Sam', reaction: null, note: null, isMe: false }] },
  { id: 'demo-activity', type: 'activity', title: 'Night street-food walk', destination: 'Gion, Kyoto', estimatedPrice: 3200, note: 'A local guide and a few small plates.', link: null, imageUrl: null, createdAt: '', addedBy: { id: 'ria', name: 'Ria' }, groupFit: { responseCount: 4, loveCount: 2, worksCount: 1, notForMeCount: 1, missingResponses: 1, hardConflict: true, status: 'needs_alignment' }, reactions: [{ userId: 'me', name: 'You', reaction: 'love', note: null, isMe: true }, { userId: 'mira', name: 'Mira', reaction: 'love', note: null, isMe: false }, { userId: 'noah', name: 'Noah', reaction: 'not_for_me', note: 'Late nights are difficult for me.', isMe: false }, { userId: 'ria', name: 'Ria', reaction: 'works', note: null, isMe: false }, { userId: 'sam', name: 'Sam', reaction: null, note: null, isMe: false }] },
  { id: 'demo-itinerary', type: 'itinerary', title: 'Kyoto at an unhurried pace', destination: 'Kyoto, Japan', estimatedPrice: 76000, note: 'Markets, small temples, and one free afternoon.', link: null, imageUrl: null, createdAt: '', addedBy: { id: 'sam', name: 'Sam' }, groupFit: { responseCount: 3, loveCount: 2, worksCount: 1, notForMeCount: 0, missingResponses: 2, hardConflict: false, status: 'waiting' }, reactions: [{ userId: 'me', name: 'You', reaction: 'love', note: null, isMe: true }, { userId: 'mira', name: 'Mira', reaction: 'works', note: null, isMe: false }, { userId: 'noah', name: 'Noah', reaction: 'love', note: null, isMe: false }, { userId: 'ria', name: 'Ria', reaction: null, note: null, isMe: false }, { userId: 'sam', name: 'Sam', reaction: null, note: null, isMe: false }] },
] }

export function QuestShortlist({ roomId, onDiscuss }: { roomId: string; onDiscuss: (title: string, detail: string) => void }) {
  const [data, setData] = useState<ShortlistData | null>(null); const [error, setError] = useState(''); const [adding, setAdding] = useState(false)
  const load = async () => { try { setError(''); setData(await getQuestShortlist(roomId)) } catch { setError('') ; setData(demo) } }
  useEffect(() => { void load() }, [roomId])
  const shown = data ?? demo
  const groups = useMemo(() => (Object.keys(category) as PickType[]).map((type) => ({ type, items: shown.sharedShortlist.filter((item) => item.type === type) })).filter((group) => group.items.length), [shown])
  return <section className="quest-shortlist" aria-labelledby="shortlist-title"><header className="shortlist-heading"><div><p className="eyebrow">POSSIBILITIES, SAVED WITH CARE</p><h2 id="shortlist-title">My Picks & <em>Shared Shortlist</em></h2><p>Keep your finds to yourself until they feel worth pinning for your people.</p></div><button className="secondary-button" type="button" onClick={() => setAdding((value) => !value)}><Icon name="plus" size={15} />Add a pick</button></header>
    {adding && <PickForm roomId={roomId} onSaved={() => { setAdding(false); void load() }} />}
    <div className="my-picks-strip"><div><p className="section-kicker">MY PICKS</p><span>{shown.myPicks.length ? `${shown.myPicks.length} private ${shown.myPicks.length === 1 ? 'find' : 'finds'}` : 'Your private travel notebook'}</span></div>{shown.myPicks.length ? <div className="my-picks-list">{shown.myPicks.map((pick) => <article key={pick.id}><strong>{pick.title}</strong><small>{category[pick.type]} · {pick.shared ? 'Shared with your group' : 'Only you can see this'}</small>{!pick.shared && <button type="button" onClick={async () => { await shareQuestPick(roomId, pick.id); void load() }}>Share with group <Icon name="arrow" size={13} /></button>}</article>)}</div> : <p className="my-picks-empty">Save a flight, stay, activity, or journey here first. Nothing is shared unless you choose it.</p>}</div>
    <div className="shortlist-readiness"><p className="section-kicker">QUEST READINESS</p><h3>{nextAction(shown.sharedShortlist)}</h3><div>{groups.map((group) => <ReadinessRow key={group.type} label={category[group.type]} items={group.items} />)}</div></div>
    <div className="shared-shortlist"><div className="shortlist-section-title"><p className="eyebrow">SHARED SHORTLIST</p><span>Everyone gets one honest response per idea.</span></div>{groups.length ? groups.map((group) => <section className="shortlist-category" key={group.type}><h3>{category[group.type]}</h3><div className="shortlist-cards">{group.items.map((item) => <SharedCard key={item.id} item={item} roomId={roomId} onChanged={load} onDiscuss={onDiscuss} />)}</div></section>) : <div className="shortlist-empty"><Icon name="spark" size={21} /><p>Your shared adventure board is ready.</p><span>Share a saved possibility when it feels like something your people should see.</span></div>}</div>{error && <p className="form-error">{error}</p>}</section>
}

function PickForm({ roomId, onSaved }: { roomId: string; onSaved: () => void }) { const [type, setType] = useState<PickType>('activity'); const [error, setError] = useState(''); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await createQuestPick(roomId, { type, title: String(form.get('title') ?? ''), destination: String(form.get('destination') ?? ''), estimatedPrice: String(form.get('price') ?? '') === '' ? '' : Number(form.get('price')), note: String(form.get('note') ?? ''), link: String(form.get('link') ?? '') }); onSaved() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save this pick.') } }; return <form className="pick-form" onSubmit={submit}><select value={type} onChange={(event) => setType(event.target.value as PickType)} aria-label="Pick type">{(Object.keys(category) as PickType[]).map((value) => <option key={value} value={value}>{category[value]}</option>)}</select><input name="title" placeholder="What did you find?" required /><input name="destination" placeholder="Destination" /><input name="price" type="number" min="0" placeholder="Estimated price" /><input name="note" placeholder="A little note for yourself" /><input name="link" type="url" placeholder="Optional link" />{error && <p className="form-error">{error}</p>}<button type="submit" className="primary-button">Save to My Picks <Icon name="arrow" size={15} /></button></form> }
function ReadinessRow({ label, items }: { label: string; items: SharedPick[] }) { const best = items.reduce((current, item) => item.groupFit.responseCount > current.groupFit.responseCount ? item : current); const note = best.groupFit.status === 'aligned' ? 'Aligned' : best.groupFit.status === 'nearly_aligned' ? 'One choice left' : best.groupFit.status === 'waiting' ? 'Waiting for voices' : 'Needs alignment'; return <div className="shortlist-readiness-row"><strong>{label}</strong><span>{best.groupFit.responseCount}/{best.reactions.length} responses · {note}</span></div> }
function nextAction(items: SharedPick[]) { if (!items.length) return 'Start by pinning one possibility.'; if (items.some((item) => item.groupFit.hardConflict)) return 'Explore an alternative that respects the concern.'; if (items.some((item) => item.groupFit.missingResponses)) return 'Invite remaining voices to weigh in.'; return 'Quest unlocked ✦' }
function SharedCard({ item, roomId, onChanged, onDiscuss }: { item: SharedPick; roomId: string; onChanged: () => void; onDiscuss: (title: string, detail: string) => void }) { const [explain, setExplain] = useState(false); const mine = item.reactions.find((reaction) => reaction.isMe); const react = async (reaction: PickReaction) => { if (reaction === 'not_for_me' && !explain) { setExplain(true); return } const note = reaction === 'not_for_me' ? window.prompt('Optional: what would make this less workable for you?') ?? '' : ''; await reactToQuestPick(roomId, item.id, reaction, note); setExplain(false); onChanged() }; const status = item.groupFit.status.replace('_', ' '); return <article className={`shared-pick-card is-${item.groupFit.status}`}><div className="shared-pick-visual">{item.imageUrl ? <img src={item.imageUrl} alt="" /> : <Icon name={item.type === 'flight' ? 'arrow' : item.type === 'stay' ? 'home' : item.type === 'activity' ? 'spark' : 'compass'} size={25} />}<span>{category[item.type]}</span></div><div className="shared-pick-body"><p className="section-kicker">{item.destination || 'A good possibility'}</p><h4>{item.title}</h4><p className="shared-pick-meta">{item.estimatedPrice ? `₹${item.estimatedPrice.toLocaleString('en-IN')} estimated` : 'Price to be checked'} · Added by {item.addedBy.name}</p>{item.note && <p className="shared-pick-note">“{item.note}”</p>}<div className="group-fit"><strong>Group Fit</strong><span className="group-fit-status">{status}</span><small>{item.groupFit.responseCount}/{item.reactions.length} voices · {item.groupFit.loveCount} love it</small></div><div className="reaction-stack" aria-label="Member reactions">{item.reactions.map((reaction) => <span key={reaction.userId} className={`reaction-avatar ${reaction.reaction ? `is-${reaction.reaction}` : 'is-pending'}`} title={`${reaction.name}: ${reaction.reaction ? labels[reaction.reaction] : 'No response yet'}`}>{reaction.name.slice(0, 1)}</span>)}</div><div className="reaction-actions">{(['love', 'works', 'not_for_me'] as PickReaction[]).map((reaction) => <button type="button" key={reaction} className={mine?.reaction === reaction ? 'is-active' : ''} onClick={() => void react(reaction)}>{labels[reaction]}</button>)}</div>{item.groupFit.hardConflict && <button type="button" className="see-alternatives" onClick={() => onDiscuss(`Alternatives to ${item.title}`, 'Could we look for another option in the same category and budget that feels better for everyone?')}>See alternatives <Icon name="arrow" size={14} /></button>}<div className="shared-pick-actions"><button type="button" onClick={() => item.link ? window.open(item.link, '_blank', 'noopener,noreferrer') : onDiscuss(item.title, item.note || 'Could we look at this option together?')}>View details</button><button type="button" onClick={() => onDiscuss(item.title, item.note || 'Could we look at this option together?')}>Discuss in chat <Icon name="chat" size={14} /></button></div></div></article> }
