import { curatedItineraries, type CuratedItinerary } from '../data/curatedItineraries'
import { demoTravellers, type TravellerProfile } from '../data/groupMockData'

export type MemberPreference = { name: string; moods: string[]; budget: string; pace: string; mustHave: string; preferredActivities?: string; noGo?: string; season?: string }
export type GroupTravelDNA = { sharedVibe: string; groupPace: string; budgetStyle: string; sharedMustHaves: string[]; flexiblePreferences: string[]; tensionsToBalance: string[]; noGoActivities: string[] }
export type Recommendation = CuratedItinerary & { score: number; minFit: number; matchedPreferences: string[]; compromises: string[]; neutralPreferences: string[] }
export type PlanPath = { id: string; title: string; label: string; description: string; itinerary: Recommendation; tradeoff: string }
const clean = (value = '') => value.toLowerCase().replace(/&/g, 'and')
const tokens = (value = '') => clean(value).split(/[^a-z]+/).filter((word) => word.length > 3)
const band = (value: string): CuratedItinerary['budgetBand'] => clean(value).includes('budget') ? 'low' : clean(value).includes('premium') ? 'premium' : 'mid'
const rhythm = (value: string): CuratedItinerary['pace'] => clean(value).includes('slow') ? 'slow' : clean(value).includes('busy') ? 'fast' : 'balanced'
const hit = (trip: CuratedItinerary, values: string[]) => values.filter((value) => trip.moods.some((mood) => clean(mood).includes(clean(value)) || clean(value).includes(clean(mood))) || trip.mustHaveTags.some((tag) => clean(value).includes(tag)))

export function deriveGroupTravelDna(members: MemberPreference[]): GroupTravelDNA {
  const moods = members.flatMap((member) => member.moods); const shared = [...new Set(moods)].filter((mood) => moods.filter((item) => item === mood).length >= Math.max(1, Math.ceil(members.length / 2)))
  const paces = members.map((member) => rhythm(member.pace)); const noGos = [...new Set(members.flatMap((member) => (member.noGo ?? '').split(/[,;]| and /i).map(value => clean(value).replace(/^(no|avoid|skip) /, '').trim()).filter(Boolean)))]
  return { sharedVibe: shared.join(' + ') || 'Curious shared discovery', groupPace: paces.includes('slow') && paces.includes('fast') ? 'A balanced rhythm with room to opt in or out' : paces[0] ?? 'A balanced rhythm', budgetStyle: [...new Set(members.map((member) => band(member.budget)))].join(' / '), sharedMustHaves: [...new Set(members.flatMap((member) => tokens(`${member.mustHave} ${member.preferredActivities ?? ''}`)))].slice(0, 5), flexiblePreferences: [...new Set(moods.filter((mood) => !shared.includes(mood)))], tensionsToBalance: paces.includes('slow') && paces.includes('fast') ? ['Restful time and one active anchor'] : [], noGoActivities: noGos }
}

export function recommendItineraries(members: MemberPreference[]): Recommendation[] {
  if (!members.length) return []
  const dna = deriveGroupTravelDna(members); const ceiling = members.some((member) => band(member.budget) === 'low') ? 'low' : members.some((member) => band(member.budget) === 'mid') ? 'mid' : 'premium'; const rank = { low: 0, mid: 1, premium: 2 }
  const filtered = curatedItineraries.filter((trip) => rank[trip.budgetBand] <= rank[ceiling] && !dna.noGoActivities.some((avoid) => { const activities = clean(JSON.stringify([trip.dayPlan, trip.avoidTags, trip.moods])); const aliases = /hik|trek|trail/.test(avoid) ? ['hik', 'trek', 'trail'] : /early|sunrise/.test(avoid) ? ['early', 'sunrise', 'dawn'] : [avoid]; return aliases.some(word => activities.includes(word)) }))
  return filtered.map((trip) => { const moods = hit(trip, members.flatMap((member) => member.moods)); const activities = hit(trip, members.flatMap((member) => tokens(`${member.mustHave} ${member.preferredActivities ?? ''}`))); const individual = members.map((member) => (hit(trip, member.moods).length + hit(trip, tokens(member.mustHave)).length) / Math.max(1, member.moods.length + 1)); const fairnessPenalty = Math.min(...individual) < .2 ? .18 : 0; const score = ((moods.length / Math.max(1, members.flatMap((member) => member.moods).length)) * .35) + ((activities.length / Math.max(1, members.length)) * .25) + ((rank[trip.budgetBand] <= rank[ceiling] ? 1 : .2) * .2) + ((members.filter((member) => rhythm(member.pace) === trip.pace).length / members.length) * .1) + ((members.some((member) => member.season && trip.bestSeasons.includes(member.season)) ? 1 : .7) * .1) - fairnessPenalty; return { ...trip, score: Math.max(0, Math.min(100, Math.round(score * 100))), minFit: Math.min(...individual), matchedPreferences: [...new Set([...moods, ...activities])].slice(0, 4), compromises: dna.tensionsToBalance.length ? dna.tensionsToBalance : ['A few individual wishes remain optional'], neutralPreferences: dna.flexiblePreferences.slice(0, 3) } }).sort((a, b) => b.score - a.score)
}
const demoMembers: MemberPreference[] = demoTravellers.map((traveller: TravellerProfile) => ({ ...traveller }))
export const getScoredItineraries = (members = demoMembers) => recommendItineraries(members)
export const getPlanPaths = (members = demoMembers): PlanPath[] => { const ranked = recommendItineraries(members); if (!ranked.length) return []; const best = ranked[0]; const fair = ranked.filter(item => item.id !== best.id).sort((a, b) => b.minFit - a.minFit || b.score - a.score)[0]; const unexpected = ranked.filter(item => item.id !== best.id && item.id !== fair?.id).sort((a, b) => Number(b.destination !== best.destination) - Number(a.destination !== best.destination) || b.score - a.score)[0]; return [{ id: 'best-shared', title: 'Best shared match', label: 'Best shared match', itinerary: best, description: 'The strongest overlap across the preferences your crew shares.', tradeoff: best.compromises[0] }, ...(fair ? [{ id: 'fair-compromise', title: 'Fair compromise', label: 'Fair compromise', itinerary: fair, description: 'A route that protects every traveller’s stated essentials.', tradeoff: fair.compromises[0] }] : []), ...(unexpected ? [{ id: 'unexpected', title: 'Unexpected match', label: 'Unexpected match', itinerary: unexpected, description: 'A fresh option that still respects the group’s foundations.', tradeoff: unexpected.compromises[0] }] : [])] }
