import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { checkInvitations } from './check-invitations.mjs'
import { checkCompanion } from './check-companion.mjs'
const base = process.env.JOURNEY_TEST_URL ?? 'http://127.0.0.1:5186'
const apiBase = process.env.JOURNEY_TEST_API_URL ?? base
assert.equal(new URL(base).hostname, '127.0.0.1', 'Browser checks must target the isolated local test runner')
assert.equal(new URL(apiBase).hostname, '127.0.0.1', 'API checks must target the isolated local test runner')
const out = resolve(process.env.JOURNEY_TEST_OUTPUT ?? '.journey-test-results')
await mkdir(out, { recursive: true })
const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL ?? 'chrome', headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
const page = await context.newPage()
page.setDefaultTimeout(12000)
const errors = []
const checks = []
page.on('pageerror', (error) => errors.push(error.message))
const screenshot = async (name, fullPage = false) => { if (fullPage) await page.evaluate(() => window.scrollTo(0, 0)); await page.screenshot({ path: `${out}/${name}.png`, fullPage }); const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1); assert.equal(overflow, false, `${name} horizontal overflow`) }
const check = (name) => { checks.push(name); console.log(`PASS ${name}`) }
const suffix = Date.now()
const email = `journey-${suffix}@example.invalid`
const password = 'Synthetic journey test 2026!'
let roomId
try {
  await page.goto(`${base}/travel-dna/new`)
  await page.waitForURL('**/login?next=*')
  assert.ok(page.url().includes('%2Ftravel-dna%2Fnew'))
  await page.getByRole('heading', { name: 'Hello again, explorer.' }).waitFor()
  await screenshot('01-sign-in')
  check('Protected route retains its destination')
  await page.getByRole('link', { name: 'Create an account', exact: false }).click()
  await page.waitForURL('**/signup?next=*')
  await screenshot('02-sign-up')
  await page.getByLabel('First name', { exact: true }).fill('Avery')
  await page.getByLabel('Last name', { exact: true }).fill('Explorer')
  await page.getByLabel('Email address', { exact: true }).fill(email)
  await page.getByLabel('Create a password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Show password', exact: true }).click()
  assert.equal(await page.locator('#account-password').getAttribute('type'), 'text')
  await page.getByLabel('Where’s home?', { exact: false }).selectOption('India')
  await page.getByRole('button', { name: 'Create my account' }).click()
  await page.waitForURL('**/travel-dna/new')
  check('Sign-up creates account and returns to protected destination')
  await page.goto(`${base}/dashboard`)
  await page.getByRole('heading', { name: 'Good to see you, Avery.' }).waitFor()
  await page.getByRole('heading', { name: 'Your first “remember when” starts here.' }).waitFor()
  await screenshot('03-dashboard-empty', true)
  await page.goto(`${base}/travel-dna/new?details=1`)
  await page.getByLabel('What shall we call this quest?').fill(`Our Kyoto chapter ${suffix}`)
  await screenshot('04-new-quest', true)
  await page.reload()
  assert.equal(await page.getByLabel('What shall we call this quest?').inputValue(), `Our Kyoto chapter ${suffix}`)
  await page.getByRole('button', { name: 'Start my quest' }).click()
  await page.getByRole('heading', { name: 'The basics.' }).waitFor()
  await page.getByRole('button', { name: 'A little more about you' }).click()
  await page.getByRole('alert').filter({ hasText: 'Choose your travel dates' }).waitFor()
  await page.getByLabel('My dates are flexible').check()
  await page.getByRole('button', { name: '5–7 days', exact: true }).click()
  await page.getByRole('button', { name: 'Friends', exact: true }).click()
  await page.getByLabel('How many people, including you?').fill('3')
  await page.getByLabel('A place on your mind').fill('Kyoto')
  await page.getByLabel('Departure city', { exact: true }).fill('Mumbai, India')
  await screenshot('05-preferences-basics', true)
  await page.getByRole('button', { name: 'A little more about you' }).click()
  assert.match(await page.getByRole('button', { name: 'Moderate', exact: true }).innerText(), /₹/)
  await page.getByRole('button', { name: 'Moderate', exact: true }).click()
  await page.getByRole('button', { name: 'Hotel', exact: true }).click()
  await screenshot('06-preferences-comfort', true)
  await page.reload()
  await page.getByRole('heading', { name: 'Your comfort zone.' }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Moderate', exact: true }).getAttribute('aria-pressed'), 'true')
  check('Quest draft, wizard step, and answers survive refresh')
  await page.getByRole('button', { name: 'A little more about you' }).click()
  await page.getByRole('button', { name: 'Food & local culture', exact: true }).click()
  await page.getByRole('button', { name: 'Nature', exact: true }).first().click()
  await page.getByRole('button', { name: 'A balanced mix', exact: true }).click()
  await screenshot('07-preferences-rhythm', true)
  await page.getByRole('button', { name: 'A little more about you' }).click()
  await page.getByLabel('The one thing you’d love', { exact: true }).fill('A local food walk')
  await screenshot('08-preferences-details', true)
  await page.getByRole('button', { name: 'Save my preferences' }).click()
  await page.waitForURL('**/quests/room_*')
  roomId = page.url().split('/').at(-1)
  await page.getByRole('button', { name: 'Make this our plan', exact: true }).first().click()
  await page.getByRole('region', { name: 'Trip workspace', exact: true }).waitFor()
  await screenshot('09-quest-workspace', true)
  check('Quest saves to database and shows real recommendations')
  await page.getByRole('navigation', { name: 'Workspace tools' }).getByRole('button', { name: 'Crew', exact: true }).click()
  await page.getByLabel('Message your crew').fill('Let’s leave room for one long lunch.')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await page.getByText('Let’s leave room for one long lunch.', { exact: true }).waitFor()
  await page.reload()
  await page.getByRole('navigation', { name: 'Workspace tools' }).getByRole('button', { name: 'Crew', exact: true }).click()
  await page.getByText('Let’s leave room for one long lunch.', { exact: true }).waitFor()
  check('Chat sends and persists across reload')
  await checkCompanion(page, { base, roomId, screenshot, check })
  await page.goto(`${base}/travel-dna/group-dna?roomId=${roomId}`)
  await page.getByRole('heading', { name: /This is how your group.*travels best/ }).waitFor()
  await screenshot('10-travel-dna', true)
  await page.getByRole('link', { name: 'See our possible paths' }).click()
  await page.getByRole('button', { name: 'Explore this itinerary' }).first().click()
  await page.locator('.itinerary-story').waitFor()
  await screenshot('11-plan-paths', true)
  check('Travel DNA and itinerary comparison load saved quest data')
  await page.goto(`${base}/travel-dna/preferences?roomId=${roomId}`)
  await page.getByRole('heading', { name: 'The basics.' }).waitFor()
  assert.equal(await page.getByLabel('A place on your mind').inputValue(), 'Kyoto')
  await page.getByRole('button', { name: 'A little more about you' }).click()
  await page.getByRole('button', { name: 'Premium', exact: true }).click()
  await page.getByRole('button', { name: 'A little more about you' }).click()
  await page.getByRole('button', { name: 'A little more about you' }).click()
  await page.getByRole('button', { name: 'Save my preferences' }).click()
  await page.waitForURL(`**/quests/${roomId}`)
  await page.goto(`${base}/trips`)
  await page.locator('.journey-quest-card').waitFor()
  assert.equal(await page.locator('.journey-quest-card').count(), 1)
  await screenshot('12-my-quests', true)
  check('Editing preferences keeps the same quest')
  await page.goto(`${base}/explore`)
  await page.locator('.explore-card').first().getByRole('button', { name: /^Save / }).click()
  await page.goto(`${base}/saved`)
  await page.locator('.explore-card').first().waitFor()
  assert.equal(await page.locator('.explore-card').count(), 1)
  await page.reload()
  await page.locator('.explore-card').first().waitFor()
  await screenshot('13-saved-places', true)
  await page.getByRole('button', { name: 'View itinerary' }).click()
  await page.getByRole('dialog').waitFor()
  await screenshot('14-itinerary-dialog')
  await page.keyboard.press('Escape')
  assert.equal(await page.getByRole('dialog').count(), 0)
  check('Saved places persist and itinerary dialog supports Escape')
  await page.goto(`${base}/profile`)
  await page.getByLabel('First name', { exact: true }).fill('Avery Updated')
  await page.getByRole('button', { name: 'Save my details' }).click()
  await page.getByRole('status').filter({ hasText: 'Your profile is updated' }).waitFor()
  await page.reload()
  await page.getByRole('heading', { name: 'Avery Updated Explorer', exact: true }).waitFor()
  await screenshot('15-profile', true)
  check('Profile updates persist through authenticated session readback')
  await page.goto(`${base}/quests/missing-room`)
  await page.getByRole('heading', { name: 'This quest isn’t in your travel book.' }).waitFor()
  check('Missing quest has a recovery state instead of infinite loading')
  await page.goto(`${base}/dashboard`)
  await page.locator('.journey-quest-card').waitFor()
  await screenshot('16-dashboard-with-quest', true)
  await page.setViewportSize({ width: 390, height: 844 })
  for (const [path, name] of [['/dashboard','17-mobile-dashboard'],['/trips','18-mobile-quests'],['/travel-dna/new','19-mobile-new-quest'],[`/travel-dna/preferences?roomId=${roomId}`,'20-mobile-preferences'],[`/quests/${roomId}`,'21-mobile-quest'],[`/travel-dna/group-dna?roomId=${roomId}`,'22-mobile-dna'],['/explore','23-mobile-explore'],['/profile','24-mobile-profile']]) {
    await page.goto(base + path)
    await page.waitForTimeout(500)
    await screenshot(name, true)
  }
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.locator('#journey-navigation').getByRole('link', { name: 'Overview' }).click()
  await page.waitForURL('**/dashboard')
  check('Mobile pages fit the viewport and navigation works')
  await checkInvitations(page, { base, roomId, password, out, check })
  await page.getByRole('button', { name: 'Open account menu' }).click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.waitForURL('**/login')
  await screenshot('25-mobile-sign-in', true)
  await page.goto(`${base}/signup`)
  await screenshot('26-mobile-sign-up', true)
  await page.goto(`${base}/login`)
  await page.getByLabel('Email address', { exact: true }).fill(email)
  await page.getByLabel('Password', { exact: true }).fill('incorrect password')
  await page.getByRole('button', { name: 'Let’s get back out there' }).click()
  await page.getByRole('alert').waitFor()
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Let’s get back out there' }).click()
  await page.waitForURL('**/dashboard')
  check('Sign-out, incorrect-password feedback, and sign-in work')
  await page.goto(`${base}/`)
  await page.locator('.gt-match').waitFor()
  await screenshot('27-mobile-landing', false)
  check('Original landing page still renders its interactive match')
  assert.deepEqual(errors, [], 'Browser runtime errors')
  await writeFile(`${out}/report.json`, JSON.stringify({ passed: checks, errors, roomId, testEmail: email, base, apiBase, screenshots: out }, null, 2))
  console.log(JSON.stringify({ result: 'passed', checks: checks.length, errors, screenshots: out }))
} catch (error) {
  await page.screenshot({ path: `${out}/failure.png`, fullPage: true })
  console.error(error)
  console.error('URL',page.url(),'BROWSER ERRORS',errors)
  process.exitCode = 1
} finally { await browser.close() }
