import { supabase } from '../supabase.js'
export type ApiEntity = Record<string, unknown> & { id: string; createdAt: string; updatedAt: string }
export type CollectionName = 'users' | 'preferences' | 'contacts' | 'itineraries' | 'flights' | 'hotels' | 'activities' | 'suggestedItineraries'
const tables: Record<CollectionName, string> = { users:'users',preferences:'preferences',contacts:'contacts',itineraries:'itineraries',flights:'flights',hotels:'hotels',activities:'activities',suggestedItineraries:'suggested_itineraries' }
const fields: Record<string,string> = { tripRoomId:'trip_room_id',dates:'dates',budget:'budget',peopleCount:'people_count',daysCount:'days_count',kidsInvolved:'kids_involved',locationPreferences:'location_preferences',moodPreferences:'mood_preferences',activitiesMustHave:'activities_must_have',activitiesPreferred:'activities_preferred',accommodationPreferences:'accommodation_preferences' }
const id=(prefix:string)=>`${prefix}_${crypto.randomUUID()}`
const entity=(row:Record<string,unknown>):ApiEntity=>({...(row.data as Record<string,unknown>),id:String(row.id),createdAt:String(row.created_at),updatedAt:String(row.updated_at)})
const check=<T>(data:T,error:{message:string}|null)=>{if(error)throw new Error(error.message);return data}
export async function list(collection:CollectionName,key?:string,value?:string){let q=supabase.from(tables[collection]).select('id,data,created_at,updated_at').order('created_at',{ascending:false});if(key==='userId'&&value)q=q.eq('user_id',value);if(key==='itineraryId'&&value)q=q.eq('itinerary_id',value);const {data,error}=await q;return check(data??[],error).map(entity)}
export async function find(collection:CollectionName,entityId:string){const {data,error}=await supabase.from(tables[collection]).select('id,data,created_at,updated_at').eq('id',entityId).maybeSingle();return check(data,error)?entity(data as Record<string,unknown>):undefined}
export async function create(collection:CollectionName,prefix:string,input:Record<string,unknown>){const table=tables[collection];const row:Record<string,unknown>={id:id(prefix),data:input};if(table!=='users')row.user_id=input.userId??null;if(['flights','hotels','activities'].includes(table))row.itinerary_id=input.itineraryId??null;if(table==='preferences')for(const[key,column]of Object.entries(fields))if(key in input)row[column]=input[key];const {data,error}=await supabase.from(table).insert(row).select('id,data,created_at,updated_at').single();return entity(check(data,error) as Record<string,unknown>)}
export async function update(collection:CollectionName,entityId:string,input:Record<string,unknown>){const existing=await find(collection,entityId);if(!existing)return undefined;const {id:_id,createdAt:_createdAt,updatedAt:_updatedAt,...data}=existing;const row:Record<string,unknown>={data:{...data,...input},updated_at:new Date().toISOString()};if(collection==='preferences')for(const[key,column]of Object.entries(fields))if(key in input)row[column]=input[key];const result=await supabase.from(tables[collection]).update(row).eq('id',entityId).select('id,data,created_at,updated_at').maybeSingle();return check(result.data,result.error)?entity(result.data as Record<string,unknown>):undefined}
export async function remove(collection:CollectionName,entityId:string){const {error,count}=await supabase.from(tables[collection]).delete({count:'exact'}).eq('id',entityId);check(null,error);return count===1}
export async function countryItineraries(country:string){const {data,error}=await supabase.from('country_itineraries').select('id,country,title,duration,budget').ilike('country',country);return check(data??[],error)}
