import { createHash, randomUUID } from 'node:crypto'
import bcrypt from 'bcryptjs'
import { supabase } from '../supabase.js'
export type PublicUser={id:string;firstName:string;lastName:string;email:string;country:string|null;createdAt:string}
type User={id:string;first_name:string|null;last_name:string|null;email:string;country:string|null;password_hash:string;created_at:string}
const publicUser=(u:User):PublicUser=>({id:u.id,firstName:u.first_name??'',lastName:u.last_name??'',email:u.email,country:u.country,createdAt:u.created_at})
const hash=(t:string)=>createHash('sha256').update(t).digest('hex')
const unwrap=<T>(data:T,error:{message:string}|null)=>{if(error)throw new Error(error.message);return data}
export async function registerUser(i:{firstName:string;lastName:string;email:string;password:string;country?:string}){const email=i.email.trim().toLowerCase();const existing=await supabase.from('users').select('id').eq('email',email).maybeSingle();if(existing.data)throw new Error('An account with this email already exists.');unwrap(null,existing.error);const id=`user_${randomUUID()}`;const passwordHash=await bcrypt.hash(i.password,12);const user={id,first_name:i.firstName.trim(),last_name:i.lastName.trim(),email,country:i.country?.trim()||null,password_hash:passwordHash,data:{name:`${i.firstName} ${i.lastName}`,email,firstName:i.firstName,lastName:i.lastName,country:i.country?.trim()||null}};const result=await supabase.from('users').insert(user).select('id,first_name,last_name,email,country,password_hash,created_at').single();return session(unwrap(result.data,result.error) as User)}
export async function loginUser(email:string,password:string){const result=await supabase.from('users').select('id,first_name,last_name,email,country,password_hash,created_at').eq('email',email.trim().toLowerCase()).maybeSingle();const user=unwrap(result.data,result.error) as User|null;if(!user||!await bcrypt.compare(password,user.password_hash))throw new Error('Email or password is incorrect.');return session(user)}
async function session(user:User){const token=randomUUID()+randomUUID();const r=await supabase.from('user_sessions').insert({id:`session_${randomUUID()}`,user_id:user.id,token_hash:hash(token),expires_at:new Date(Date.now()+2592000000).toISOString()});unwrap(null,r.error);return{user:publicUser(user),token}}
export async function userForToken(token:string){const s=await supabase.from('user_sessions').select('user_id').eq('token_hash',hash(token)).gt('expires_at',new Date().toISOString()).maybeSingle();const session=unwrap(s.data,s.error) as {user_id:string}|null;if(!session)return undefined;const r=await supabase.from('users').select('id,first_name,last_name,email,country,password_hash,created_at').eq('id',session.user_id).maybeSingle();const user=unwrap(r.data,r.error) as User|null;return user?publicUser(user):undefined}
export async function endSession(token:string){const r=await supabase.from('user_sessions').delete().eq('token_hash',hash(token));unwrap(null,r.error)}
