import type { CreateRoomInput, Room } from '../models/room.js'
import { supabase } from '../supabase.js'
import { createTripRoomInvite } from './invitationService.js'
const map=(r:Record<string,unknown>):Room=>({id:String(r.id),name:String(r.name),tripName:String(r.trip_name),members:Number(r.members),createdAt:String(r.created_at)})
const unwrap=<T>(data:T,error:{message:string}|null)=>{if(error)throw new Error(error.message);return data}
export async function listRooms(){const r=await supabase.from('trip_rooms').select('id,name,trip_name,members,created_at').order('created_at',{ascending:false});return (unwrap(r.data??[],r.error) as Record<string,unknown>[]).map(map)}
export async function listUserRooms(userId:string){const r=await supabase.from('trip_room_people').select('role,invite_status,trip_rooms(id,name,trip_name,members,status,created_at)').eq('user_id',userId).order('created_at',{ascending:false});const rows=unwrap(r.data??[],r.error) as Array<Record<string,unknown>>;return rows.flatMap((row)=>{const room=row.trip_rooms as Record<string,unknown>|null;return room?[{...map(room),role:String(row.role),inviteStatus:String(row.invite_status)}]:[]})}
export async function createRoom(input:CreateRoomInput & { inviteEmail?: string; ownerId?: string }){const r=await supabase.from('trip_rooms').insert({id:`room_${crypto.randomUUID()}`,name:input.name.trim(),trip_name:input.tripName.trim(),members:input.members??1}).select('id,name,trip_name,members,created_at').single();const room=map(unwrap(r.data,r.error) as Record<string,unknown>);if(input.ownerId){const membership=await supabase.from('trip_room_people').upsert({trip_room_id:room.id,user_id:input.ownerId,role:'owner',invite_status:'accepted'},{onConflict:'trip_room_id,user_id'});unwrap(membership.data,membership.error)}const invite=input.inviteEmail?.trim()?await createTripRoomInvite(room,input.inviteEmail):undefined;return {...room,invite}}
export async function inviteToRoom(roomId:string,email:string){const r=await supabase.from('trip_rooms').select('id,name').eq('id',roomId).maybeSingle();const room=unwrap(r.data,r.error) as Record<string,unknown>|null;if(!room)return undefined;return createTripRoomInvite({id:String(room.id),name:String(room.name)},email)}
export async function updateRoom(id:string,input:Partial<CreateRoomInput>){const r=await supabase.from('trip_rooms').update({...(input.name?.trim()?{name:input.name.trim()}:{}),...(input.tripName?.trim()?{trip_name:input.tripName.trim()}:{}),...(typeof input.members==='number'?{members:input.members}:{}),updated_at:new Date().toISOString()}).eq('id',id).select('id,name,trip_name,members,created_at').maybeSingle();return unwrap(r.data,r.error)?map(r.data as Record<string,unknown>):undefined}
