import type { Request, Response } from 'express'
import { analyseQuestNotes, applyQuestNote, dismissQuestNote, getQuestNotesState, setQuestNotesEnabled } from '../services/questNotesService.js'
import { userForToken } from '../services/authService.js'
const bearer = (header?: string) => header?.startsWith('Bearer ') ? header.slice(7) : ''
const roomId = (request: Request) => String(request.params.roomId ?? '')
async function user(request: Request, response: Response) { const current = await userForToken(bearer(request.header('authorization'))); if (!current) response.status(401).json({ error: 'Please sign in to use Quest Notes.' }); return current }
export async function getQuestNotes(request: Request, response: Response) { const current = await user(request, response); if (!current) return; try { response.json({ data: await getQuestNotesState(roomId(request), current.id) }) } catch (error) { response.status(403).json({ error: error instanceof Error ? error.message : 'Could not load Quest Notes.' }) } }
export async function patchQuestNotes(request: Request, response: Response) { const current = await user(request, response); if (!current) return; try { response.json({ data: await setQuestNotesEnabled(roomId(request), current.id, Boolean(request.body?.enabled)) }) } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : 'Could not update Quest Notes.' }) } }
export async function analyseNotes(request: Request, response: Response) { const current = await user(request, response); if (!current) return; try { response.json({ data: await analyseQuestNotes(roomId(request), current.id) }) } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : 'Could not analyse this conversation.' }) } }
export async function applyNote(request: Request, response: Response) { const current = await user(request, response); if (!current) return; try { response.json({ data: await applyQuestNote(roomId(request), current.id, String(request.params.noteId ?? ''), request.body?.action === 'must_have' ? 'must_have' : 'nice_to_have') }) } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : 'Could not apply this Quest Note.' }) } }
export async function dismissNote(request: Request, response: Response) { const current = await user(request, response); if (!current) return; try { response.json({ data: await dismissQuestNote(roomId(request), current.id, String(request.params.noteId ?? '')) }) } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : 'Could not dismiss this Quest Note.' }) } }
