import type { Request, Response } from 'express'
import { userForToken } from '../services/authService.js'
import { createPick, getShortlist, reactToSharedPick, sharePick } from '../services/shortlistService.js'
const bearer = (header?: string) => header?.startsWith('Bearer ') ? header.slice(7) : ''
const param = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value ?? ''
async function user(request: Request, response: Response) { const current = await userForToken(bearer(request.header('authorization'))); if (!current) response.status(401).json({ error: 'Please sign in to manage your quest picks.' }); return current }
export async function getShortlistController(request: Request, response: Response) { const current = await user(request, response); if (!current) return; try { response.json({ data: await getShortlist(param(request.params.roomId), current.id) }) } catch (error) { response.status(403).json({ error: error instanceof Error ? error.message : 'Could not load the shortlist.' }) } }
export async function postPickController(request: Request, response: Response) { const current = await user(request, response); if (!current) return; try { response.status(201).json({ data: await createPick(param(request.params.roomId), current.id, request.body ?? {}) }) } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : 'Could not save this pick.' }) } }
export async function postSharePickController(request: Request, response: Response) { const current = await user(request, response); if (!current) return; try { await sharePick(param(request.params.roomId), current.id, param(request.params.pickId)); response.json({ data: { ok: true } }) } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : 'Could not share this pick.' }) } }
export async function postReactionController(request: Request, response: Response) { const current = await user(request, response); if (!current) return; try { await reactToSharedPick(param(request.params.roomId), current.id, param(request.params.sharedPickId), request.body ?? {}); response.json({ data: { ok: true } }) } catch (error) { response.status(400).json({ error: error instanceof Error ? error.message : 'Could not save that reaction.' }) } }
