import { Link } from 'react-router-dom'
import { useState } from 'react'
import { deriveGroupTravelDna, getPlanPaths, type PlanPath } from '../services/recommendationEngine'
import { demoTravellers } from '../data/groupMockData'
import { personaliseItinerary } from '../services/companionApi'

type Story = { resultTitle: string; scrapbookIntro: string; whyItWorks: string[]; tradeoffNote: string; days: Array<{ day: number; title: string; description: string; highlights: string[]; mood: string }> }
export function PlanPathsPage() {
  const [story, setStory] = useState<Story | null>(null); const [loading, setLoading] = useState<string | null>(null); const paths = getPlanPaths(); const dna = deriveGroupTravelDna(demoTravellers)
  const choose = async (path: PlanPath) => { setLoading(path.id); try { const result = await personaliseItinerary(dna, path.itinerary, { matchedPreferences: path.itinerary.matchedPreferences, compromises: path.itinerary.compromises, neutralPreferences: path.itinerary.neutralPreferences }); setStory(result.data) } catch { setStory({ resultTitle: path.itinerary.title, scrapbookIntro: path.itinerary.shortDescription, whyItWorks: path.itinerary.matchedPreferences.length ? path.itinerary.matchedPreferences : ['Curated for the group’s shared travel rhythm.'], tradeoffNote: path.tradeoff, days: path.itinerary.dayPlan }) } finally { setLoading(null) } }
  return <section className="flow-page paths-page"><div className="flow-topbar"><Link className="back-link" to="/travel-dna/group-dna">← Group DNA</Link><span className="flow-step">Choose together</span></div><div className="flow-heading"><p className="eyebrow">Curated for your crew</p><h1>Choose a path that feels <em>fair.</em></h1><p className="lede">These routes are calculated from your group’s stated preferences—not from an AI guess.</p></div><div className="path-grid">{paths.map((path) => <article className="path-card" key={path.id}><img src={path.itinerary.image} alt="" /><div><span className="path-label">{path.label}</span><p className="section-kicker">{path.itinerary.destination}</p><h2>{path.itinerary.title}</h2><p>{path.description}</p><small><b>Trade-off:</b> {path.tradeoff}</small><button className="text-button" type="button" onClick={() => choose(path)}>{loading === path.id ? 'Turning your group’s plan into a travel story…' : 'Open itinerary'} <span>→</span></button></div></article>)}</div>{story && <section className="path-note itinerary-story"><p className="section-kicker">Travel journal</p><h2>{story.resultTitle}</h2><p>{story.scrapbookIntro}</p><ul>{story.whyItWorks.map((item) => <li key={item}>{item}</li>)}</ul><small><b>Fair trade-off:</b> {story.tradeoffNote}</small><div className="story-days">{story.days.map((day) => <article key={day.day}><b>Day {day.day}</b><h3>{day.title}</h3><p>{day.description}</p></article>)}</div></section>}</section>
}
