import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'
import { countries } from '../data/countries'
import { Icon, PageHeading } from '../components/Ui'
export function ProfilePage() {
  const { user, updateProfile } = useAuth()
  const [firstName, setFirstName] = useState(user!.firstName)
  const [lastName, setLastName] = useState(user!.lastName)
  const [country, setCountry] = useState(user!.country ?? '')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [saved, setSaved] = useState(false)
  const save = async (event: FormEvent) => { event.preventDefault(); if (busy) return; setBusy(true); setError(''); setSaved(false); try { await updateProfile({ firstName: firstName.trim(), lastName: lastName.trim(), country }); setSaved(true) } catch (reason) { setError(reason instanceof Error ? reason.message : 'We couldn’t update your profile. Please try again.') } finally { setBusy(false) } }
  return <section><PageHeading eyebrow="THE PERSON BEHIND THE PLANS" title={<>A little more <em>you.</em></>} description="Your home base for all the places you’re yet to go." /><div className="profile-layout"><aside className="profile-identity"><span className="profile-monogram">{user!.firstName[0]}{user!.lastName[0]}</span><p className="eyebrow">A FELLOW EXPLORER</p><h2>{user!.firstName} {user!.lastName}</h2><p>{user!.email}</p>{user!.country && <p><Icon name="pin" size={14} /> {user!.country}</p>}<span>Part of the journey since {new Intl.DateTimeFormat('en', { month: 'long', year: 'numeric' }).format(new Date(user!.createdAt))}</span></aside><section className="profile-edit"><h2>Your everyday details.</h2><p>So your crew knows who’s coming along.</p><form onSubmit={save} onChange={() => setSaved(false)}><div className="field-row"><label>First name<input value={firstName} onChange={(event) => setFirstName(event.target.value)} autoComplete="given-name" required maxLength={60} /></label><label>Last name<input value={lastName} onChange={(event) => setLastName(event.target.value)} autoComplete="family-name" required maxLength={60} /></label></div><label>Email address<input type="email" value={user!.email} disabled /><span className="field-hint">Your sign-in and invitation address.</span></label><label>Where’s home?<select value={country} onChange={(event) => setCountry(event.target.value)} autoComplete="country-name"><option value="">Choose your country</option>{countries.map((item) => <option key={item}>{item}</option>)}</select></label>{error && <p className="form-error" role="alert">{error}</p>}{saved && <p className="invite-success" role="status">Your profile is updated. Looking good for the next chapter.</p>}<button className="primary-button" type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save my details'}<Icon name="check" size={18} /></button></form><div className="profile-links"><Link to="/crew">My crew <Icon name="people" size={15} /></Link><Link to="/travel-style">My travel style & perks <Icon name="leaf" size={15} /></Link><Link to="/trips">Your quests <Icon size={15} /></Link><Link to="/saved">Your saved places <Icon name="heart" size={15} /></Link></div></section></div></section>
}
