import { useEffect, useState, type FormEvent } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { getQuestMessages, getUserQuests, inviteToQuest, sendQuestMessage, type Quest, type QuestMessage } from '../apis/quests'
import { useAuth } from '../auth/AuthContext'

export function QuestDetailPage() {
  const { roomId = '' } = useParams(); const { user, ready } = useAuth(); const [quest, setQuest] = useState<Quest | null>(null); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [chatMessages, setChatMessages] = useState<QuestMessage[]>([]); const [chatText, setChatText] = useState(''); const [chatError, setChatError] = useState(''); const [sendingChat, setSendingChat] = useState(false)
  useEffect(() => { if (user) getUserQuests(user.id).then((items) => setQuest(items.find((item) => item.id === roomId) ?? null)).catch((reason: Error) => setError(reason.message)) }, [roomId, user])
  useEffect(() => {
    if (!user || !roomId) return
    let mounted = true
    const refresh = () => getQuestMessages(roomId).then((items) => { if (mounted) setChatMessages(items) }).catch((reason: Error) => { if (mounted) setChatError(reason.message) })
    refresh()
    const timer = window.setInterval(refresh, 5_000)
    return () => { mounted = false; window.clearInterval(timer) }
  }, [roomId, user])
  if (!ready) return null; if (!user) return <Navigate to="/login" replace />
  const invite = async (event: FormEvent) => { event.preventDefault(); setError(''); setMessage(''); try { const result = await inviteToQuest(roomId, email); setMessage(result.delivered ? `Invitation sent to ${result.email}.` : result.reason ?? `Invitation created for ${result.email}, but delivery could not be completed.`); setEmail('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not send the invitation.') } }
  const sendChat = async (event: FormEvent) => { event.preventDefault(); if (!chatText.trim()) return; setSendingChat(true); setChatError(''); try { const created = await sendQuestMessage(roomId, chatText); setChatMessages((current) => [...current, created]); setChatText('') } catch (reason) { setChatError(reason instanceof Error ? reason.message : 'Could not send this message.') } finally { setSendingChat(false) } }
  if (!quest && !error) return <section className="flow-page"><p className="lede">Loading your quest…</p></section>
  if (!quest) return <section className="flow-page"><Link className="back-link" to="/plan">← Your quests</Link><p className="form-error">{error || 'This quest is unavailable.'}</p></section>
  return <section className="flow-page quest-detail-page"><div className="flow-topbar"><Link className="back-link" to="/plan">← Your quests</Link><span className="room-live"><i /> {quest.role === 'owner' ? 'Quest host' : 'Quest member'}</span></div><div className="overview-hero"><p className="eyebrow">{quest.tripName}</p><h1>{quest.name}</h1><p className="lede">{quest.members} travellers are planned for this quest. Keep building the group whenever you are ready.</p></div><div className="overview-grid"><section className="overview-panel"><p className="section-kicker">Quest details</p><h2>Your journey</h2><div className="answer-list"><div><span>Destination</span><strong>{quest.tripName}</strong></div><div><span>Group size</span><strong>{quest.members} travellers</strong></div><div><span>Role</span><strong>{quest.role === 'owner' ? 'Quest host' : 'Crew member'}</strong></div></div></section><section className="overview-panel suggestion-panel"><p className="section-kicker">Grow your crew</p><h2>Invite another traveller.</h2><p>They’ll receive a secure link to sign in or create an account, then join this quest.</p><form className="quest-invite-form" onSubmit={invite}><label htmlFor="quest-invite-email">Email address<input id="quest-invite-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="friend@example.com" required /></label>{error && <p className="form-error">{error}</p>}{message && <p className="invite-success">{message}</p>}<button className="primary-button" type="submit">Send invitation <span>→</span></button></form></section></div><section className="quest-chat" aria-label="Quest chat"><div className="quest-chat-heading"><div><p className="section-kicker">Crew conversation</p><h2>Plan it together.</h2></div><span>Updates every 5 seconds</span></div><div className="chat-thread" aria-live="polite">{!chatMessages.length && !chatError && <p className="chat-empty">Start the conversation—share an idea, a question, or a travel wish.</p>}{chatMessages.map((item) => <article className={item.senderId === user.id ? 'chat-message mine' : 'chat-message'} key={item.id}><div><strong>{item.senderId === user.id ? 'You' : item.senderName}</strong><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</time></div><p>{item.body}</p></article>)}</div><form className="chat-composer" onSubmit={sendChat}><label className="sr-only" htmlFor="quest-chat-message">Message your crew</label><textarea id="quest-chat-message" rows={2} maxLength={2000} value={chatText} onChange={(event) => setChatText(event.target.value)} placeholder="Share an idea with your crew…" /><button className="primary-button" type="submit" disabled={sendingChat}>{sendingChat ? 'Sending…' : 'Send'} <span>→</span></button></form>{chatError && <p className="form-error">{chatError}</p>}</section></section>
}
