import { useEffect, useState, type FormEvent } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { getUserQuests, inviteToQuest, type Quest } from '../apis/quests'
import { useAuth } from '../auth/AuthContext'

export function QuestDetailPage() {
  const { roomId = '' } = useParams(); const { user, ready } = useAuth(); const [quest, setQuest] = useState<Quest | null>(null); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  useEffect(() => { if (user) getUserQuests(user.id).then((items) => setQuest(items.find((item) => item.id === roomId) ?? null)).catch((reason: Error) => setError(reason.message)) }, [roomId, user])
  if (!ready) return null; if (!user) return <Navigate to="/login" replace />
  const invite = async (event: FormEvent) => { event.preventDefault(); setError(''); setMessage(''); try { const result = await inviteToQuest(roomId, email); setMessage(result.delivered ? `Invitation sent to ${result.email}.` : result.reason ?? `Invitation created for ${result.email}, but delivery could not be completed.`); setEmail('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not send the invitation.') } }
  if (!quest && !error) return <section className="flow-page"><p className="lede">Loading your quest…</p></section>
  if (!quest) return <section className="flow-page"><Link className="back-link" to="/plan">← Your quests</Link><p className="form-error">{error || 'This quest is unavailable.'}</p></section>
  return <section className="flow-page quest-detail-page"><div className="flow-topbar"><Link className="back-link" to="/plan">← Your quests</Link><span className="room-live"><i /> {quest.role === 'owner' ? 'Quest host' : 'Quest member'}</span></div><div className="overview-hero"><p className="eyebrow">{quest.tripName}</p><h1>{quest.name}</h1><p className="lede">{quest.members} travellers are planned for this quest. Keep building the group whenever you are ready.</p></div><div className="overview-grid"><section className="overview-panel"><p className="section-kicker">Quest details</p><h2>Your journey</h2><div className="answer-list"><div><span>Destination</span><strong>{quest.tripName}</strong></div><div><span>Group size</span><strong>{quest.members} travellers</strong></div><div><span>Role</span><strong>{quest.role === 'owner' ? 'Quest host' : 'Crew member'}</strong></div></div></section><section className="overview-panel suggestion-panel"><p className="section-kicker">Grow your crew</p><h2>Invite another traveller.</h2><p>They’ll receive a secure link to sign in or create an account, then join this quest.</p><form className="quest-invite-form" onSubmit={invite}><label htmlFor="quest-invite-email">Email address<input id="quest-invite-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="friend@example.com" required /></label>{error && <p className="form-error">{error}</p>}{message && <p className="invite-success">{message}</p>}<button className="primary-button" type="submit">Send invitation <span>→</span></button></form></section></div></section>
}
