import { useEffect, useState, type FormEvent } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { getQuestMessages, getQuestRecommendations, getUserQuests, inviteToQuest, sendQuestMessage, type Quest, type QuestMessage, type QuestRecommendation } from '../apis/quests'
import { useAuth } from '../auth/AuthContext'
import { personaliseItinerary } from '../services/companionApi'

export function QuestDetailPage() {
  const { roomId = '' } = useParams(); const { user, ready } = useAuth(); const [quest, setQuest] = useState<Quest | null>(null); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [chatMessages, setChatMessages] = useState<QuestMessage[]>([]); const [chatText, setChatText] = useState(''); const [chatError, setChatError] = useState(''); const [sendingChat, setSendingChat] = useState(false)
  useEffect(() => { if (user) getUserQuests(user.id).then((items) => setQuest(items.find((item) => item.id === roomId) ?? null)).catch((reason: Error) => setError(reason.message)) }, [roomId, user])
  useEffect(() => {
    if (!user || !roomId) return
    let mounted = true
    const refresh = () => getQuestMessages(roomId).then((items) => { if (mounted) setChatMessages(items) }).catch((reason: Error) => { if (mounted) setChatError(reason.message) })
    refresh()
    const timer = window.setInterval(refresh, 5_000)
    return () => { mounted = false; window.clearInterval(timer) }
  }, [roomId, user])
  if (!ready) return null; if (!user) return <Navigate to="/login" replace />
  const invite = async (event: FormEvent) => { event.preventDefault(); setError(''); setMessage(''); try { const result = await inviteToQuest(roomId, email); setMessage(result.delivered ? `Invitation sent to ${result.email}.` : result.reason ?? `Invitation created for ${result.email}, but delivery could not be completed.`); setEmail('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not send the invitation.') } }
  const sendChat = async (event: FormEvent) => { event.preventDefault(); if (!chatText.trim()) return; setSendingChat(true); setChatError(''); try { const created = await sendQuestMessage(roomId, chatText); setChatMessages((current) => [...current, created]); setChatText('') } catch (reason) { setChatError(reason instanceof Error ? reason.message : 'Could not send this message.') } finally { setSendingChat(false) } }
  if (!quest && !error) return <section className="flow-page"><p className="lede">Loading your quest…</p></section>
  if (!quest) return <section className="flow-page"><Link className="back-link" to="/plan">← Your quests</Link><p className="form-error">{error || 'This quest is unavailable.'}</p></section>
  return <section className="flow-page quest-detail-page"><div className="flow-topbar"><Link className="back-link" to="/plan">← Your quests</Link><span className="room-live"><i /> {quest.role === 'owner' ? 'Quest host' : 'Quest member'}</span></div><div className="overview-hero"><p className="eyebrow">{quest.tripName}</p><h1>{quest.name}</h1><p className="lede">{quest.members} travellers are planned for this quest. Keep building the group whenever you are ready.</p></div><div className="overview-grid"><section className="overview-panel"><p className="section-kicker">Quest details</p><h2>Your journey</h2><div className="answer-list"><div><span>Destination</span><strong>{quest.tripName}</strong></div><div><span>Group size</span><strong>{quest.members} travellers</strong></div><div><span>Role</span><strong>{quest.role === 'owner' ? 'Quest host' : 'Crew member'}</strong></div></div></section><section className="overview-panel suggestion-panel"><p className="section-kicker">Grow your crew</p><h2>Invite another traveller.</h2><p>They’ll receive a secure link to sign in or create an account, then join this quest.</p><form className="quest-invite-form" onSubmit={invite}><label htmlFor="quest-invite-email">Email address<input id="quest-invite-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="friend@example.com" required /></label>{error && <p className="form-error">{error}</p>}{message && <p className="invite-success">{message}</p>}<button className="primary-button" type="submit">Send invitation <span>→</span></button></form></section></div><QuestSuggestions roomId={roomId} /><section className="quest-chat" aria-label="Quest chat"><div className="quest-chat-heading"><div><p className="section-kicker">Crew conversation</p><h2>Plan it together.</h2></div><span>Updates every 5 seconds</span></div><div className="chat-thread" aria-live="polite">{!chatMessages.length && !chatError && <p className="chat-empty">Start the conversation—share an idea, a question, or a travel wish.</p>}{chatMessages.map((item) => <article className={item.senderId === user.id ? 'chat-message mine' : 'chat-message'} key={item.id}><div><strong>{item.senderId === user.id ? 'You' : item.senderName}</strong><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</time></div><p>{item.body}</p></article>)}</div><form className="chat-composer" onSubmit={sendChat}><label className="sr-only" htmlFor="quest-chat-message">Message your crew</label><textarea id="quest-chat-message" rows={2} maxLength={2000} value={chatText} onChange={(event) => setChatText(event.target.value)} placeholder="Share an idea with your crew…" /><button className="primary-button" type="submit" disabled={sendingChat}>{sendingChat ? 'Sending…' : 'Send'} <span>→</span></button></form>{chatError && <p className="form-error">{chatError}</p>}</section></section>
}

function QuestSuggestions({ roomId }: { roomId: string }) { const [story, setStory] = useState<{ resultTitle: string; scrapbookIntro: string; whyItWorks: string[]; tradeoffNote: string } | null>(null); const [selected, setSelected] = useState<QuestRecommendation | null>(null); const [loading, setLoading] = useState<string | null>(null); const [data, setData] = useState<{ travelDna: unknown; results: QuestRecommendation[] } | null>(null); const [error, setError] = useState(''); useEffect(() => { getQuestRecommendations(roomId).then(setData).catch((reason: Error) => setError(reason.message)) }, [roomId]); const open = async (trip: QuestRecommendation) => { setSelected(trip); setLoading(trip.id); try { const result = await personaliseItinerary(data?.travelDna, trip, { matchedPreferences: trip.matchedPreferences, compromises: trip.compromises }); setStory(result.data) } catch { setStory({ resultTitle: trip.title, scrapbookIntro: trip.short_description, whyItWorks: trip.matchedPreferences, tradeoffNote: trip.compromises[0] ?? 'This is a flexible starting point.' }) } finally { setLoading(null) } }; return <section className="quest-suggestions"><div className="flow-section-heading"><div><p className="section-kicker">Suggested itineraries</p><h2>Your group’s next possibilities</h2></div></div>{error && <p className="form-error">{error}</p>}{!data && !error && <p className="form-hint">Matching your saved preferences with the curated collection…</p>}<div className="path-grid">{data?.results.map((trip) => <article className="path-card" key={trip.id}><div><span className="path-label">{trip.label}</span><p className="section-kicker">{trip.destination}, {trip.country}</p><h2>{trip.title}</h2><p>{trip.short_description}</p><small>{trip.duration_days} days · {trip.budget} · {trip.matchedPreferences.join(', ') || 'Balanced group fit'}</small><button type="button" className="text-button" onClick={() => open(trip)}>{loading === trip.id ? 'Turning your group’s plan into a travel story…' : 'Open itinerary'} <span>→</span></button></div></article>)}</div>{story && selected && <article className="path-note itinerary-story"><p className="section-kicker">Your travel story</p><h2>{story.resultTitle}</h2><p>{story.scrapbookIntro}</p><ul>{story.whyItWorks.map((item) => <li key={item}>{item}</li>)}</ul><small><b>Fair trade-off:</b> {story.tradeoffNote}</small><TravelPlanningOptions trip={selected} /></article>}</section> }

function TravelPlanningOptions({ trip }: { trip: QuestRecommendation }) { const stay = trip.budget === 'Premium' ? 'Boutique hotel or resort' : trip.budget === 'Budget-friendly' ? 'Guesthouse or apartment stay' : 'Design hotel or home rental'; return <section className="travel-planning-options"><div><p className="section-kicker">Build your trip</p><h3>Flights & stays</h3><small>Curated planning options — not live prices or availability.</small></div><div className="travel-option-grid"><article><span>✈</span><p>Flight approach</p><strong>Compare flexible arrival options into {trip.destination}</strong><small>Choose the best departure city and timing for your crew before booking.</small></article><article><span>⌂</span><p>Stay style</p><strong>{stay}</strong><small>Best aligned with this {trip.budget.toLowerCase()} itinerary and its {trip.duration_days}-day pace.</small></article></div></section> }
